kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.10-alpine3.16
  pull: if-not-exists
  commands:
  - pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple
  - mkdocs build
- name: docker  
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: harbor_name
    password:
      from_secret: harbor_password
    registry: harbor.heysq.com:8443
    repo: harbor.heysq.com:8443/library/nginx-mkdocs
    tags: latest
    dockerfile: Dockerfile
    mirror: https://hub-mirror.c.163.com
- name: deploy
    image: zc2638/drone-k8s-plugin
    pull: if-not-exists
    settings:
      k8s_server: https://192.168.110.2:16443
      k8s_token:
        from_secret: k8s_token
      k8s_ca_crt:
        from_secret: k8s_ca
      k8s_skip_tls: false
      namespace: default
      templates:
        - kubernetes.yaml
      app_name: mkdocs
  