kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.10-alpine3.16
  commands:
  - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk add --no-cache nginx \
    && pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple \
    && mkdocs build
- name: docker  
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: 192.168.110.2:20003
    repo: 192.168.110.2:20003/nginx-mkdocs
    tags: latest
    dockerfile: Dockerfile
    mirror: https://hub-mirror.c.163.com