kind: pipeline
type: docker
name: default

steps:
- name: build
  image: registry.cn-beijing.aliyuncs.com/aliyun_wiki/mkdocs_basic:v1
  pull: if-not-exists
  commands:
  - mkdocs build
  when:
    branch:
    - dev
- name: docker-pro
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: aliyun_name
    password:
      from_secret: aliyun_password
    registry: registry.cn-beijing.aliyuncs.com
    repo: registry.cn-beijing.aliyuncs.com/aliyun_wiki/mkdocs_site
    tags: latest
    dockerfile: Dockerfile
  when:
    branch:
    - master
- name: docker-dev
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: aliyun_name
    password:
      from_secret: aliyun_password
    registry: registry.cn-beijing.aliyuncs.com
    repo: registry.cn-beijing.aliyuncs.com/aliyun_wiki/mkdocs_site
    tags: dev
    dockerfile: Dockerfile
  when:
    branch:
    - dev
- name: deploy-dev
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host:
      - home.heysq.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - kubectl rollout restart deployment mkdocs-deployment-dev -n mkdocs-dev
  when:
    branch:
    - dev
- name: deploy-pro
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host:
      - home.heysq.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - kubectl rollout restart deployment mkdocs-deployment -n mkdocs
  when:
    branch:
    - master
trigger:
  branch:
  - master
  - dev
  event:
  - push