kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.10-alpine3.16
  commands:
  - pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple
  - mkdocs build
- name: docker  
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: hub.heysq.com:8443
    repo: hub.heysq.com:8443/nginx-mkdocs
    tags: latest
    dockerfile: Dockerfile
    mirror: https://hub-mirror.c.163.com