kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.10-alpine3.16
  pull: if-not-exists
  commands:
  - pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple
  - mkdocs build
- name: docker  
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: harbor_name
    password:
      from_secret: harbor_password
    registry: harbor.heysq.com:8443
    repo: harbor.heysq.com:8443/library/nginx-mkdocs
    tags: latest
    dockerfile: Dockerfile
    mirror: https://hub-mirror.c.163.com