kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.10-alpine3.16
  pull: if-not-exists
  commands:
  - pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple
  - mkdocs build
  when:
    branch:
    - dev
- name: docker-pro
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: harbor_name
    password:
      from_secret: harbor_password
    registry: harbor.heysq.com:8443
    repo: harbor.heysq.com:8443/library/nginx-mkdocs
    tags: latest
    dockerfile: Dockerfile
  when:
    branch:
    - master
- name: docker-dev
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: harbor_name
    password:
      from_secret: harbor_password
    registry: harbor.heysq.com:8443
    repo: harbor.heysq.com:8443/library/nginx-mkdocs
    tags: dev
    dockerfile: Dockerfile
  when:
    branch:
    - dev
- name: deploy-dev
  image: appleboy/drone-ssh
  settings:
    host:
      - www.heysq.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - kubectl rollout restart deployment mkdocs-deployment-dev
  when:
    branch:
    - dev
- name: deploy-pro
  image: appleboy/drone-ssh
  settings:
    host:
      - www.heysq.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - kubectl rollout restart deployment mkdocs-deployment
  when:
    branch:
    - master
trigger:
  branch:
  - master
  - dev