apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment-dev
  namespace: mkdocs-dev
spec:
  selector:
    matchLabels:
      app: mkdocs-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: mkdocs-dev
    spec:
      imagePullSecrets:
      - name: aliyun-registry
      containers:
      - name: mkdocs-dev
        image: registry.cn-beijing.aliyuncs.com/aliyun_wiki/mkdocs_site:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80