apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment-dev
  namespace: default
spec:
  selector:
    matchLabels:
      app: mkdocs-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: mkdocs-dev
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
      - name: mkdocs-dev
        image: harbor.heysq.com:8443/library/nginx-mkdocs:dev
        ports:
        - containerPort: 80