apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
  namespace: mkdocs
spec:
  selector:
    matchLabels:
      app: mkdocs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      imagePullSecrets:
      - name: aliyun-registry
      containers:
      - name: mkdocs
        image: registry.cn-beijing.aliyuncs.com/aliyun_wiki/mkdocs_site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80