apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: mkdocs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
      - name: mkdocs
        image: harbor.heysq.com:8443/library/nginx-mkdocs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80