site_name: Sunqi's Wiki
repo_url: https://gitee.com/sunqi43797189/mkdocs_wiki
repo_name: sunqi43797189/wiki
theme:
  name: material
  language: 'zh'
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.top
  custom_dir: 'material_theme'
  features:
    - navigation.top
    - header.autohide
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
nav:
  - Home: index.md
  - Go:
    - 简述: golang/desc.md
    - Map: golang/map.md
    - SyncMap: golang/sync_map.md
    - Go并发: golang/go_complicate.md
    - Goroutine && Thread: golang/goroutine_thread.md 
    - GMP: golang/gmp.md
    - GMP机制: golang/gmp_detail.md
    - Goroutine 状态: golang/goroutine_status.md
    - Goroutine 泄漏: golang/goroutine_xielou.md
    - 限流算法&&限流器: golang/xianliu.md
    - Channel: golang/channel.md
    - Go开源项目: golang/go_project.md
    - Go Modules构建模式: golang/go_mod.md
    - Go Mod6个常规操作: golang/go_mod_operate.md
    - 代码块&&作用域: golang/daimakuai.md
    - 数值类型: golang/data_type.md
    - 字符串类型: golang/string_type.md
    - 常量: golang/changliang.md
    - 数组&&切片: golang/array_slice.md
    - 杂项: golang/zaxiang.md
    - 结构体: golang/struct.md
    - panic&&recover: golang/panic_recover.md
    - 条件&&循环: golang/condition.md
    - 函数: golang/function.md
    - 方法: golang/method.md
    - 接口: golang/interface.md
    - 类型嵌入: golang/leixingqianru.md
    
  - Kafka:
    - Kafka: kafka/kafka.md
  - MySQL:
    - 查询语句: mysql/查询语句.md 
    - 更新语句: mysql/更新语句.md 
    - 事务隔离: mysql/事务隔离.md
    - 索引: mysql/索引.md
    - 各种锁: mysql/各种锁.md
    - 脏页: mysql/脏页.md
    - 表: mysql/表.md
    - 不同的count: mysql/不同的count.md
    - 两阶段提交: mysql/两阶段提交_崩溃恢复.md
    - order_by: mysql/order_by.md
    - SQL执行异常: mysql/sql执行异常.md
    - 幻读: mysql/幻读.md
    - 可重复读: mysql/可重复读加锁规则.md
    - binlog&&redolog: mysql/binlog_redolog.md
    - 主备一致: mysql/主备一致.md
    - 杂项: mysql/zaxiang.md

  - Redis:
    - 布隆过滤器: redis/布隆过滤器.md
    - Scan: redis/scan.md
    - Hash: redis/hash.md
    - SDS简单动态字符串: redis/sds.md
    
  - 计算机网络:
    - 数据链路层: http/数据链路层.md  
    - 网络层: http/网络层.md
    - 传输层: http/传输层.md
    - 网络安全: http/网络安全.md
    - HTTPS: http/https.md
    - HTTP升级改进: http/http升级改造.md
  - VIM:
    - vimrc: vim/vimrc.md 
  - IDE:
    - VsCode背景图: ide/vscode_background.md
  - 计算机组成:
    - 冯诺依曼体系结构: jsjzc/fnym.md 
    - 寄存器: jsjzc/jicunqi.md
    - 程序栈: jsjzc/chengxuzhan.md
    - 程序装载: jsjzc/cxzz.md
    - 门电路: jsjzc/mdl.md
    - 浮点数和定点数: jsjzc/fds&&dds.md
    - CPU: jsjzc/cpu.md
    - 流水线: jsjzc/lsx.md
    - CPU加速: jsjzc/cpu加速.md
    - 异常&&中断: jsjzc/yc&&zd.md
    - 指令集CISC和RISC: jsjzc/zlj.md
    - GPU: jsjzc/gpu.md
    - 局部性原理: jsjzc/jbx.md
    - 高速缓存: jsjzc/gshc.md
    - 内存: jsjzc/neicun.md
    - 总线: jsjzc/zongxian.md
    - DMA: jsjzc/dma.md