site_name: Sunqi's Wiki
repo_url: https://gitee.com/sunqi43797189/mkdocs_wiki
repo_name: sunqi43797189/wiki
theme:
  name: material
  language: 'zh'
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.top
  custom_dir: 'material_theme'
  features:
    - navigation.top
    - header.autohide
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
nav:
  - Home: index.md
  - Golang:
    - Map: golang/map.md
    - SyncMap: golang/sync_map.md
    - Goroutine && Thread: golang/goroutine_thread.md 
    - GMP: golang/gmp.md
    - GMP机制: golang/gmp_detail.md
    - Goroutine 状态: golang/goroutine_status.md
    - Goroutine 泄漏: golang/goroutine_xielou.md
    - 限流算法&&限流器: golang/xianliu.md
    - Channel: golang/channel.md
  - Kafka:
    - Kafka: kafka/kafka.md
  - MySQL:
    - 查询语句: mysql/查询语句.md 
    - 更新语句: mysql/更新语句.md 
    - 事务隔离: mysql/事务隔离.md
    - 索引: mysql/索引.md
    - 各种锁: mysql/各种锁.md
    - 脏页: mysql/脏页.md
    - 表: mysql/表.md
    - 不同的count: mysql/不同的count.md
    - 两阶段提交: mysql/两阶段提交_崩溃恢复.md
    - order_by: mysql/order_by.md
    - SQL执行异常: mysql/sql执行异常.md
    - 幻读: mysql/幻读.md
    - 可重复读: mysql/可重复读加锁规则.md
    - binlog&&redolog: mysql/binlog_redolog.md
    - 主备一致: mysql/主备一致.md
  - Redis:
    - 布隆过滤器: redis/布隆过滤器.md
    - Scan: redis/scan.md
  - HTTP:
    - 数据链路层: http/数据链路层.md  
    - 网络层: http/网络层.md
    - 传输层: http/传输层.md
    - 网络安全: http/网络安全.md
    - HTTPS: http/https.md
    - HTTP升级改进: http/http升级改造.md
  - VIM:
    - vimrc: vim/vimrc.md 
  - IDE:
    - VsCode背景图: ide/vscode_background.md
  - 计算机组成:
    - 冯诺依曼体系结构: jsjzc/fnym.md 
    - 寄存器: jsjzc/jicunqi.md
    - 程序栈: jsjzc/chengxuzhan.md
    - 程序装载: jsjzc/cxzz.md
    - 门电路: jsjzc/mdl.md
    - 浮点数和定点数: jsjzc/fds&&dds.md