site_name: Sun's Wiki
nav:
  - Home: index.md
  - Kafka: kafka.md
  - MySQL:
    - 查询语句: mysql/查询语句.md 
    - 更新语句: mysql/更新语句.md 
    - 事务隔离: mysql/事务隔离.md
    - 索引: mysql/索引.md
    - 各种锁: mysql/各种锁.md
    - 脏页: mysql/脏页.md
    - 表: mysql/表.md
    - 不同的count: mysql/不同的count.md
    - 两阶段提交: mysql/两阶段提交_崩溃恢复.md
  - Redis: redis.md
theme:
  name: material
  language: 'zh'
  palette:
    scheme: default
  features:
    - navigation.top
