site_name: Sun's Wiki
nav:
  - Home: index.md
  - Kafka: kafka.md
  - MySQL:
    - 查询语句: mysql/查询语句.md 
    - 更新语句: mysql/更新语句.md 
  - Redis: redis.md
theme:
  name: material
  language: 'zh'
  palette:
    scheme: default
  features:
    - navigation.top
