site_name: Sunqi's Wiki
repo_url: https://github.com/Sunqi43797189/mkdocs_wiki
repo_name: Sunqi43797189/mkdocs_wiki
theme:
  name: material
  language: 'zh'
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.top
  custom_dir: 'material_theme'
  features:
    - navigation.top
    - header.autohide
plugins:
  - search
  # - progress
  - literate-nav:
      nav_file: nav.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
